name: Schedule Latest Build Docker -with-full-mod

on:
  # schedule:
  #   - cron: '25 23 * * *'
  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'LICENSE'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: set full mod flag
      run: sed -i "s/#usefullmod//g" makeiso.sh
    - name: Set SHSHA
      run: echo "SHSHA="$(echo "${{ github.sha }}"|grep -Eo "^[0-9a-z]{7}"|head -1) >> $GITHUB_ENV
    - name: Gen sha.txt
      run: echo "${{ env.SHSHA }}" >sha.txt
    - name: Set TAG_NAME
      run: echo "TAG_NAME=""$(date +%Y%m%d)"""-"${{ env.SHSHA }}" >> $GITHUB_ENV
    - name: build iso
      run: sh makeiso.sh
    - name: Set variables
      run:  echo "RE_NOTE=$(cat ./iso/renote.txt | tr -d '[:space:]')" >> $GITHUB_ENV
    - name: show iso sha256sum
      run: cat ./iso/renote.txt
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push -with-full-mod
      uses: docker/build-push-action@v4
      with:
        context: "./iso"
        push: true
        platforms: linux/amd64
        tags: sliamb/ppgwiso:fullmod